# Site settings
title: hzijone
subTitle: Just another Jekyll blog.
email: huangzhigang@junda-tech.com
description: > # love to open source, love to share
#baseurl: "jundahzijone.github.io" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  jundahzijone


####################################################
#author add
# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

#Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: date
paginate: 5
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

coderay:
  coderay_wrap:              div
  coderay_line_numbers:      inline
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_bold_every:        10
  coderay_css:               style


  # pygments: true
  # markdown: redcarpet
  # redcarpet:
  #   extensions:
  #     - hard_wrap
  #     - no_intra_emphasis
  #     - autolink
  #     - strikethrough
  #     - fenced_code_blocks

# author 
link: http://www.zhanxin.info/contact.html


#theme config
themes: /themes/violet

#top backgroud map
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 作品
    url: /works.html
  - text: 联系我
    url: /contact.html
  - text: 博客源代码
    url: https://github.com/jundahzijone/jundahzijone.github.io


#关注我
follow:
  - class: fa-google-plus
    url: http://jundahzijone.github.io
  - class: fa-facebook
    url: http://jundahzijone.github.io
  - class: fa-github
    url: http://github.com/pizn
  - class: fa-weibo
    url: http://weibo.com/pizner
  - class: fa-renren
    url: http://jundahzijone.github.io
  - class: fa-pinterest
    url: http://jundahzijone.github.io
  - class: fa-twitter
    url: http://jundahzijone.github.io
  - class: fa-rss
    url: http://jundahzijone.github.io